### ISSUE TITLE
Seahub doesn't remove links to removed folders

### ISSUE THREAD

**Issue by khorkin** [haiwen/seahub#1899]
Hi,
seahub doesn't remove links to removed folders/files.
How to reproduce:
1. Create Folder 'testFolder'
2. Create File 'testFile'
3. Create DownLoad link to file: FileDonwLoadlink
4. Create DownLoad link to folder: FolderDonwLoadlink
5. Create Upload link to folder: FolderUploadLink
6. Remove file and folder
7. Look into Share Admin Links page

Expected results
- No shared link presents

Actual results:
- All created links are exists

**Comment by omkarnathsingh** [comment]
These bugs should be solved, its been a long time.

**Comment by yuyichao** [comment]
This issue is not fixed. The link is still there after the file is deleted (obviously they don't work anymore). The link also stops working but still point to th same path after the original folder is renamed.

This seems like a security trap since one could have an old dysfunctional link to a non-existing path that isn't meant to be shared anymore. However, if the directly is created again, the content will be accessible through the old link even if the user did not intend so.
